version: "3.8"

services:
  hostingbot:
    build: .
    container_name: hostingbot
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./logs:/app/logs
      - ./extracted:/app/extracted
      - ./pending:/app/pending
      - ./sites:/app/sites
      - ./temp:/app/temp
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: python3 src/main.py