services:
  - type: web
    name: hostingbot
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false           # secret – not stored in repo
      - key: OWNER_ID
        value: 8760823326
      - key: ADMIN_ID
        value: 8760823326
      - key: OWNER_NAME
        value: Blac
      - key: UPDATE_CHANNEL
        value: https://t.me/TechTipsCode
      - key: SUPPORT_CHANNEL
        value: https://t.me/EliteCodeLab
      - key: OWNER_USERNAME
        value: https://t.me/blcqt
      - key: USE_DOCKER
        value: "true"
      - key: DOCKER_IMAGE
        value: hostingbot-sandbox
      - key: PORT
        value: 5000